<h2 class="sub-header">Cargos</h2>
<a href="?action=insert">Insertar un nuevo Cargo</a>
<br/>
<table class="table table-striped">
<?php foreach($filas as $key => $fila):?>
	<tr>
		<?php 
		foreach ($fila as $columna):?>
			<td><?=$columna;?></td>
		<?php endforeach; ?>
		<td>
			<a href="?action=update&id=<?=$fila['idduty'];?>">Actualizar</a>
				&nbsp;
			<a href="?action=delete&id=<?=$fila['idduty'];?>">Borrar</a>
		</td>
	</tr>
<?php endforeach ?>
</table>