<h2 class="sub-header">Proyectos</h2>
<a href="?action=insert">Insertar Proyecto</a>
<br/>

<table class="table table-striped">
 
<?php foreach($filas as $key => $fila):?>
	<tr>
		<?php 
		foreach ($fila as $columna):?>
			<td><?=$columna;?></td>
		<?php endforeach; ?>

		<td>
			<a href="?action=update&id=<?=$fila['idproject'];?>">Actualizar</a>
				&nbsp;
			<a href="?action=delete&id=<?=$fila['idproject'];?>">Borrar</a>
		</td>
	</tr>
<?php endforeach ?>
</table>