<form class="form-signin" role="form" method="post">
<h2 class="form-signin-heading">Identificate o Muere</h2>
<input type="email" name="email" class="form-control" placeholder="Email address" required autofocus>
<input type="password" name="password" class="form-control" placeholder="Password" required>
<label class="checkbox">
<input type="checkbox" name="remmeberme" value="remember-me"> Recordar
</label>
<button class="btn btn-lg btn-primary btn-block" type="submit">Identificarse</button>
</form>